// Generated by ml.export.generate_phase7_e2e; cloud SHA-256: 533c57db42219b68d807756ae140ed505fb25e1b0a5e45ca4eeb500b5031468c
#pragma once
constexpr const char* EXPECTED_CLASSES[] = {"IDLE", "SWIPE_LEFT", "SWIPE_RIGHT", "ROTATE_CW", "SHAKE"};
constexpr float EXPECTED_CONFIDENCES[] = {9.991884828e-01f, 9.997170568e-01f, 9.732206464e-01f, 9.999990463e-01f, 9.999911785e-01f};
