"""Export float32 Split1 tail and validate against frozen prefix parity vectors."""

import json

import numpy as np
import tensorflow as tf

from ml.models.cloud_tail_split1 import (
    CLOUD_TAIL_VERSION, MODEL_DIR, MODEL_PATH, SOURCE_MODEL_VERSION,
    validate_cloud_tail_split1,
)
from ml.training.train_cloud_tail import sha256_file
from ml.dataset.loader import CLASS_TO_ID


def write_firmware_expectations(probabilities, model_sha256):
    """Generate only the isolated E2E test's expected cloud responses."""
    names = {value: key for key, value in CLASS_TO_ID.items()}
    classes = ", ".join(json.dumps(names[int(row.argmax())]) for row in probabilities)
    confidences = ", ".join(f"{float(row.max()):.9e}f" for row in probabilities)
    path = (MODEL_DIR.parents[5] / "firmware/test/test_phase7_split1_e2e"
            / "cloud_expectations.h")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by ml.export.export_split1_cloud_tail; Keras SHA-256:\n"
        f"// {model_sha256}\n#pragma once\n"
        f"constexpr const char* EXPECTED_CLASSES[] = {{{classes}}};\n"
        f"constexpr float EXPECTED_CONFIDENCES[] = {{{confidences}}};\n",
        encoding="utf-8",
    )


def run_tail_tflite(path, embeddings):
    interpreter = tf.lite.Interpreter(model_path=str(path), num_threads=1)
    interpreter.allocate_tensors()
    inp, = interpreter.get_input_details()
    out, = interpreter.get_output_details()
    for detail, shape in ((inp, (1, 64)), (out, (1, 5))):
        if tuple(detail["shape"]) != shape or detail["dtype"] != np.float32:
            raise ValueError("Split1 tail TFLite shape/dtype mismatch")
    outputs = []
    for row in embeddings:
        interpreter.set_tensor(inp["index"], np.asarray(row, dtype=np.float32)[None])
        interpreter.invoke()
        outputs.append(interpreter.get_tensor(out["index"])[0])
    return np.asarray(outputs)


def main() -> None:
    output = MODEL_DIR / f"{CLOUD_TAIL_VERSION}.tflite"
    parity_path = MODEL_DIR / "split1_cloud_parity_vectors.npz"
    if output.exists() or parity_path.exists():
        raise RuntimeError("Refusing to overwrite Split1 export evidence")
    model = tf.keras.models.load_model(MODEL_PATH, compile=False)
    validate_cloud_tail_split1(model)
    report_path = MODEL_DIR / "split1_export_report.json"
    report = json.loads(report_path.read_text(encoding="utf-8"))
    if sha256_file(MODEL_PATH) != report["model_sha256"]:
        raise RuntimeError("Split1 Keras hash mismatch")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = []
    output.write_bytes(converter.convert())
    prefix_vectors = (MODEL_DIR.parent / SOURCE_MODEL_VERSION / "tflite/splits"
                      / "split1_parity_vectors.npz")
    with np.load(prefix_vectors) as vectors:
        embeddings = vectors["tflite_split1"].copy()
        expected = model(embeddings, training=False).numpy()
        actual = run_tail_tflite(output, embeddings)
        np.testing.assert_allclose(actual, expected, atol=2e-5, rtol=0)
        np.testing.assert_array_equal(actual.argmax(1), expected.argmax(1))
        np.savez_compressed(parity_path, embeddings=embeddings,
                            expected_probabilities=expected, tflite_probabilities=actual,
                            normalized_inputs=vectors["normalized_inputs"],
                            true_classes=vectors["true_classes"])
    report.update({"tflite_exported": True, "quantized": False,
                   "tflite_sha256": sha256_file(output), "tflite_bytes": output.stat().st_size,
                   "parity_vector_count": len(embeddings), "parity_tolerance": 2e-5,
                   "keras_tflite_max_abs_diff": float(np.max(np.abs(expected - actual))),
                   "prefix_vectors_sha256": sha256_file(prefix_vectors)})
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_firmware_expectations(expected, report["model_sha256"])
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
