"""Generate fixed cloud-response expectations and Split3 vectors for hardware tests."""

import argparse
import json

import numpy as np

from ml.export.generate_split1_firmware import matrix_to_cpp, write_new_file
from ml.export.split_validation import ROOT, MODELS
from ml.dataset.loader import CLASS_TO_ID
from ml.training.train_cloud_tail import sha256_file


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--split", type=int, choices=(2, 3), required=True)
    split = parser.parse_args().split
    version = "gesture-cloud-tail-v1.0.0" if split == 3 else "gesture-cloud-tail-split2-v1.0.0"
    directory = MODELS / version
    names = {value: key for key, value in CLASS_TO_ID.items()}
    with np.load(directory / f"split{split}_cloud_parity_vectors.npz") as vectors:
        probabilities = vectors["expected_probabilities"]
        classes = ", ".join(json.dumps(names[int(row.argmax())]) for row in probabilities)
        confidences = ", ".join(f"{float(row.max()):.9e}f" for row in probabilities)
        digest = sha256_file(directory / f"{version}.keras")
        write_new_file(ROOT / f"firmware/test/test_phase7_split{split}_e2e/cloud_expectations.h",
                       f"// Generated by ml.export.generate_phase7_e2e; cloud SHA-256: {digest}\n"
                       "#pragma once\n"
                       f"constexpr const char* EXPECTED_CLASSES[] = {{{classes}}};\n"
                       f"constexpr float EXPECTED_CONFIDENCES[] = {{{confidences}}};\n")
        if split == 3:
            write_new_file(ROOT / "firmware/test/test_phase7_split3_parity/split3_parity_vectors.h", f'''#pragma once
#include <stddef.h>
namespace split3_parity_vectors {{
constexpr size_t VECTOR_COUNT = 5;
constexpr float NORMALIZED_INPUTS[5][10] = {{
{matrix_to_cpp(vectors['normalized_inputs'])}
}};
constexpr float EXPECTED_OUTPUTS[5][32] = {{
{matrix_to_cpp(vectors['expected_split3'])}
}};
}}
''')


if __name__ == "__main__":
    main()
