// Generated by ml.export.generate_phase7_e2e; cloud SHA-256: 9a834eecf909374488fe346c89b34310bd6c7fdb58570ed2ffb0c885535866d1
#pragma once
constexpr const char* EXPECTED_CLASSES[] = {"IDLE", "SWIPE_LEFT", "SWIPE_RIGHT", "ROTATE_CW", "SHAKE"};
constexpr float EXPECTED_CONFIDENCES[] = {9.974330068e-01f, 9.994677901e-01f, 9.589192271e-01f, 9.999876022e-01f, 9.999387264e-01f};
