// Generated by ml.export.export_split1_cloud_tail; Keras SHA-256:
// ce144c368964f74da96da6ca77c00d35e2de0577f605ac54d458475454191b9c
#pragma once
constexpr const char* EXPECTED_CLASSES[] = {"IDLE", "SWIPE_LEFT", "SWIPE_RIGHT", "ROTATE_CW", "SHAKE"};
constexpr float EXPECTED_CONFIDENCES[] = {9.996368885e-01f, 9.999047518e-01f, 9.886553288e-01f, 1.000000000e+00f, 9.999995232e-01f};
