[platformio]
default_envs = esp32-s3-n8r2

[env:esp32-s3-n8r2]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3